DROP TABLE IF EXISTS jobseekers;
CREATE TABLE jobseekers (
id INT AUTO_INCREMENT PRIMARY KEY,
seeker_id VARCHAR(15) UNIQUE NOT NULL,
seeker_Name VARCHAR(15) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
birth_6 VARCHAR(6) NOT NULL,
phone VARCHAR(13) NOT NULL,
email VARCHAR(50) NOT NULL,
industry VARCHAR(200),
location VARCHAR(200)
)DEFAULT CHARSET=utf8;
commit;